services:

#  weather-etl:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: weather-etl:latest
#    container_name: weather-etl
#    env_file:
#      - .env.cloud
#    restart: unless-stopped
#    networks:
#      - monitoring

  postgres:
    image: postgres:latest
    container_name: postgres-native
    command: ["-c", "listen_addresses=*"]
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/18/docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres-user -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql
    networks:
      - monitoring
      - pg-network

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    restart: unless-stopped
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - /home/medun/loki/data:/loki
    networks:
      - monitoring
      - security

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
      - security
      - trades_stream_network

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - "127.0.0.1:9091:9091"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - /home/medun/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring
      - security

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: some@email.com
      PGADMIN_DEFAULT_PASSWORD: pgapass
    restart: unless-stopped
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - monitoring

  portainer:
    image: portainer/portainer-ce:sts
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8001:8000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock


  prefect-server:
    image: prefecthq/prefect:3-python3.12
    container_name: prefect-server
    command: prefect server start --host 0.0.0.0
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: ${PREFECT_API_DATABASE_CONNECTION_URL}
    restart: unless-stopped
    ports:
      - "127.0.0.1:4200:4200"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:4200/api/health')"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - monitoring
      - pg-network



  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prefect-worker
    command: prefect worker start --pool local-dev-process
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    restart: unless-stopped
    depends_on:
      prefect-server:
        condition: service_healthy
    networks:
      - monitoring
      - pg-network










volumes:

  my_postgres_data:
    external: true

  grafana_data:
    external: true

  prometheus_data:
    external: true
    name: 8ae23a6b83dbae9e2fd0f4474eefdc000af06f1419c012dbd4ec878a49b58c2c

  pgadmin_data:
    external: true
    name: 7ae1ceed6d0bb84741be73ff8fdfade4fa10a30c61163d37f2b767cb2e8dc5cd

  portainer_data:
    external: true

networks:

  monitoring:
    external: true

  pg-network:
    external: true

  security:
    external: true

  trades_stream_network:
    external: true























#services:
#  weather-etl:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: weather-etl:latest
#    container_name: weather-etl-test
#    env_file:
#      - .env.cloud
#    networks:
#      - monitoring
#networks:
#  monitoring:
#    external: true
#
#
#  postgres:
#    image: postgres:latest
#    container_name: postgres-native
#    command: ["-c", "listen_addresses=*"]
#    environment:
#      POSTGRES_USER: postgres-user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: postgres
#      PGDATA: /var/lib/postgresql/18/docker
#    ports:
#      - "5432:5432"
#    volumes:
#      - my_postgres_data:/var/lib/postgresql
#    networks:
#      - monitoring
#      - pg-network
#
#  loki:
#    image: grafana/loki:2.9.1
#    container_name: loki
#    command:
#      - "-config.file=/etc/loki/local-config.yaml"
#    ports:
#      - "127.0.0.1:3100:3100"
#    volumes:
#      - /home/medun/loki/data:/loki
#    networks:
#      - monitoring
#      - security
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - "127.0.0.1:3000:3000"
#    volumes:
#      - grafana_data:/var/lib/grafana
#    networks:
#      - monitoring
#      - security
#      - trades_stream_network
#
#  pushgateway:
#    image: prom/pushgateway
#    container_name: pushgateway
#    ports:
#      - "127.0.0.1:9091:9091"
#    networks:
#      - monitoring
#
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yml"
#      - "--storage.tsdb.path=/prometheus"
#    ports:
#      - "127.0.0.1:9090:9090"
#    volumes:
#      - /home/medun/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
#    networks:
#      - monitoring
#      - security
#
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: some@email.com
#      PGADMIN_DEFAULT_PASSWORD: pgapass
#    ports:
#      - "5050:80"
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    networks:
#      - monitoring
#
#  portainer:
#    image: portainer/portainer-ce:sts
#    container_name: portainer
#    ports:
#      - "8001:8000"
#      - "9443:9443"
#    volumes:
#      - portainer_data:/data
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - bridge
#
#
#volumes:
#
#  my_postgres_data:
#    external: true
#
#  grafana_data:
#    external: true
#
#  prometheus_data:
#    external: true
#    name: 8ae23a6b83dbae9e2fd0f4474eefdc000af06f1419c012dbd4ec878a49b58c2c
#
#  pgadmin_data:
#    external: true
#    name: 7ae1ceed6d0bb84741be73ff8fdfade4fa10a30c61163d37f2b767cb2e8dc5cd
#
#  portainer_data:
#    external: true
#
#
#networks:
#
#  monitoring:
#    external: true
#
#  pg-network:
#    external: true
#
#  security:
#    external: true
#
#  trades_stream_network:
#    external: true
#
#  bridge:
#    external: true
#
#
#
#
#
#
#
#
##services:
##  weather-etl:
##    image: weather-etl:latest
##    container_name: weather-etl-test
##    env_file:
##      - .env.cloud
##    networks:
##      - monitoring
##
##networks:
##  monitoring:
##    external: true