name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint
        run: ruff check .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: pchelkovskiy/weather-data-platform:latest

      - name: Check syntax
        run: python -m compileall .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_admin_object_id: ${{ secrets.ADMIN_OBJECT_ID }}
          TF_VAR_db_host: ${{ secrets.TF_VAR_DB_HOST }}
          TF_VAR_db_name_scraped: ${{ secrets.TF_VAR_DB_NAME_SCRAPED }}
          TF_VAR_db_name_raw: ${{ secrets.TF_VAR_DB_NAME_RAW }}
          TF_VAR_db_name_transformed: ${{ secrets.TF_VAR_DB_NAME_TRANSFORMED }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_TENANT_ID }}
          TF_VAR_client_id: ${{ secrets.TF_VAR_CLIENT_ID }}
          TF_VAR_account_url: ${{ secrets.TF_VAR_ACCOUNT_URL }}
          TF_VAR_file_system: ${{ secrets.TF_VAR_FILE_SYSTEM }}
          TF_VAR_prefect_api_url: ${{ secrets.TF_VAR_PREFECT_API_URL }}
          TF_VAR_project_dir: ${{ secrets.TF_VAR_PROJECT_DIR }}
          TF_VAR_loki_url: ${{ secrets.TF_VAR_LOKI_URL }}
          TF_VAR_prometheus_remote_write_url: ${{ secrets.TF_VAR_PROMETHEUS_REMOTE_WRITE_URL }}

